version: '3.9'
services:
  7dtdserver:
    # image: vinanrra/7dtd-server
    container_name: 7dtdserver
    labels:
      co.elastic.logs/enabled: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - START_MODE=1 #Change between START MODES
      - VERSION=stable # Change between 7 days to die versions
      - PUID=1000 # Remember to use same as your user
      - PGID=1000 # Remember to use same as your user
      - TimeZone=Europe/Madrid # Optional - Change Timezone
      - TEST_ALERT=NO # Optional - Send a test alert
      - UPDATE_MODS=NO # Optional - This will allow mods to be update on start, each mod also need to have XXXX_UPDATE=YES to update on start
      - ALLOC_FIXES=NO # Optional - Install ALLOC FIXES
      - ALLOC_FIXES_UPDATE # Optional - Update Allocs Fixes before server start
      - UNDEAD_LEGACY=NO # Optional - Install Undead Legacy mod
      - UNDEAD_LEGACY_VERSION=stable # Optional - Undead Legacy version
      - UNDEAD_LEGACY_UPDATE=NO # Optional - Update Undead Legacy mod before server start
      - ENZOMBIES=NO # Optional - Install EnZombies mod
      - ENZOMBIES_ADDON_SNUFKIN=NO # Optional - Install EnZombies addon mod
      - ENZOMBIES_ADDON_ROBELOTO=NO # Optional - Install EnZombies addon mod
      - ENZOMBIES_ADDON_NONUDES=NO # Optional - Install EnZombies addon mod
      - ENZOMBIES_UPDATE=NO # Optional - Update EnZombies mod and addons before server start
      - CPM=NO # Optional - CSMM Patron's Mod (CPM)
      - CPM_UPDATE=NO # Optional - Update CPM before server start
      - BEPINEX=NO # Optional - BepInEx
      - BEPINEX_UPDATE=NO # Optional - Update BepInEx before server start
      - BACKUP=YES # Optional - Backup server at 5 AM
      - MONITOR=YES # Optional - Keeps server up if crash
    volumes:
      - ~/7dtd-server/7DaysToDie:/home/sdtdserver/.local/share/7DaysToDie/
      - ~/7dtd-server/LGSM-Config:/home/sdtdserver/lgsm/config-lgsm/sdtdserver
      - ~/7dtd-server/ServerFiles:/home/sdtdserver/serverfiles/ # Optional - serverfiles folder
      - ~/7dtd-server/log:/home/sdtdserver/log/ # Optional - Logs folder
      - ~/7dtd-server/backups:/home/sdtdserver/lgsm/backup/ # Optional - If BAKCUP=NO, backups folder
    ports:
      - 26900:26900/tcp # Default game ports
      - 26900:26900/udp # Default game ports
      - 26901:26901/udp # Default game ports
      - 26902:26902/udp # Default game ports
      - 7080:8080/tcp # OPTIONAL - WEBADMIN
      - 7081:8081/tcp # OPTIONAL - TELNET
      - 7082:8082/tcp # OPTIONAL - WEBSERVER https://7dtd.illy.bz/wiki/Server%20fixes
    restart: unless-stopped # INFO - NEVER USE WITH START_MODE=4 or START_MODE=0
